// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.snowcattle.game.auto;

public final class LoginMessageProto {
  private LoginMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2S_LoginMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2S_LoginMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1 [default = ""];</code>
     *
     * <pre>
     *玩家用户名
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1 [default = ""];</code>
     *
     * <pre>
     *玩家用户名
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1 [default = ""];</code>
     *
     * <pre>
     *玩家用户名
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string password = 2 [default = ""];</code>
     *
     * <pre>
     *玩家密码
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2 [default = ""];</code>
     *
     * <pre>
     *玩家密码
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2 [default = ""];</code>
     *
     * <pre>
     *玩家密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional int32 webid = 3 [default = 0];</code>
     *
     * <pre>
     *平台Id
     * </pre>
     */
    boolean hasWebid();
    /**
     * <code>optional int32 webid = 3 [default = 0];</code>
     *
     * <pre>
     *平台Id
     * </pre>
     */
    int getWebid();

    /**
     * <code>optional int32 serverId = 4 [default = 0];</code>
     *
     * <pre>
     *服务器Id
     * </pre>
     */
    boolean hasServerId();
    /**
     * <code>optional int32 serverId = 4 [default = 0];</code>
     *
     * <pre>
     *服务器Id
     * </pre>
     */
    int getServerId();
  }
  /**
   * Protobuf type {@code C2S_LoginMessage}
   *
   * <pre>
   *登陆消息
   * </pre>
   */
  public static final class C2S_LoginMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:C2S_LoginMessage)
      C2S_LoginMessageOrBuilder {
    // Use C2S_LoginMessage.newBuilder() to construct.
    private C2S_LoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2S_LoginMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2S_LoginMessage defaultInstance;
    public static C2S_LoginMessage getDefaultInstance() {
      return defaultInstance;
    }

    public C2S_LoginMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_LoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              webid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              serverId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.snowcattle.game.auto.LoginMessageProto.internal_static_C2S_LoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.snowcattle.game.auto.LoginMessageProto.internal_static_C2S_LoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.class, com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<C2S_LoginMessage> PARSER =
        new com.google.protobuf.AbstractParser<C2S_LoginMessage>() {
      public C2S_LoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_LoginMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_LoginMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1 [default = ""];</code>
     *
     * <pre>
     *玩家用户名
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1 [default = ""];</code>
     *
     * <pre>
     *玩家用户名
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1 [default = ""];</code>
     *
     * <pre>
     *玩家用户名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 2 [default = ""];</code>
     *
     * <pre>
     *玩家密码
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2 [default = ""];</code>
     *
     * <pre>
     *玩家密码
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2 [default = ""];</code>
     *
     * <pre>
     *玩家密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEBID_FIELD_NUMBER = 3;
    private int webid_;
    /**
     * <code>optional int32 webid = 3 [default = 0];</code>
     *
     * <pre>
     *平台Id
     * </pre>
     */
    public boolean hasWebid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 webid = 3 [default = 0];</code>
     *
     * <pre>
     *平台Id
     * </pre>
     */
    public int getWebid() {
      return webid_;
    }

    public static final int SERVERID_FIELD_NUMBER = 4;
    private int serverId_;
    /**
     * <code>optional int32 serverId = 4 [default = 0];</code>
     *
     * <pre>
     *服务器Id
     * </pre>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 serverId = 4 [default = 0];</code>
     *
     * <pre>
     *服务器Id
     * </pre>
     */
    public int getServerId() {
      return serverId_;
    }

    private void initFields() {
      name_ = "";
      password_ = "";
      webid_ = 0;
      serverId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, webid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, serverId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, webid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, serverId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_LoginMessage}
     *
     * <pre>
     *登陆消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2S_LoginMessage)
        com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.snowcattle.game.auto.LoginMessageProto.internal_static_C2S_LoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.snowcattle.game.auto.LoginMessageProto.internal_static_C2S_LoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.class, com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.Builder.class);
      }

      // Construct using com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        webid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.snowcattle.game.auto.LoginMessageProto.internal_static_C2S_LoginMessage_descriptor;
      }

      public com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage getDefaultInstanceForType() {
        return com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.getDefaultInstance();
      }

      public com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage build() {
        com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage buildPartial() {
        com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage result = new com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.webid_ = webid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverId_ = serverId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage) {
          return mergeFrom((com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage other) {
        if (other == com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasWebid()) {
          setWebid(other.getWebid());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.snowcattle.game.auto.LoginMessageProto.C2S_LoginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1 [default = ""];</code>
       *
       * <pre>
       *玩家用户名
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       *
       * <pre>
       *玩家用户名
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       *
       * <pre>
       *玩家用户名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       *
       * <pre>
       *玩家用户名
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       *
       * <pre>
       *玩家用户名
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       *
       * <pre>
       *玩家用户名
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2 [default = ""];</code>
       *
       * <pre>
       *玩家密码
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2 [default = ""];</code>
       *
       * <pre>
       *玩家密码
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2 [default = ""];</code>
       *
       * <pre>
       *玩家密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2 [default = ""];</code>
       *
       * <pre>
       *玩家密码
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2 [default = ""];</code>
       *
       * <pre>
       *玩家密码
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2 [default = ""];</code>
       *
       * <pre>
       *玩家密码
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      private int webid_ ;
      /**
       * <code>optional int32 webid = 3 [default = 0];</code>
       *
       * <pre>
       *平台Id
       * </pre>
       */
      public boolean hasWebid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 webid = 3 [default = 0];</code>
       *
       * <pre>
       *平台Id
       * </pre>
       */
      public int getWebid() {
        return webid_;
      }
      /**
       * <code>optional int32 webid = 3 [default = 0];</code>
       *
       * <pre>
       *平台Id
       * </pre>
       */
      public Builder setWebid(int value) {
        bitField0_ |= 0x00000004;
        webid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 webid = 3 [default = 0];</code>
       *
       * <pre>
       *平台Id
       * </pre>
       */
      public Builder clearWebid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        webid_ = 0;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <code>optional int32 serverId = 4 [default = 0];</code>
       *
       * <pre>
       *服务器Id
       * </pre>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 serverId = 4 [default = 0];</code>
       *
       * <pre>
       *服务器Id
       * </pre>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>optional int32 serverId = 4 [default = 0];</code>
       *
       * <pre>
       *服务器Id
       * </pre>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000008;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 serverId = 4 [default = 0];</code>
       *
       * <pre>
       *服务器Id
       * </pre>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:C2S_LoginMessage)
    }

    static {
      defaultInstance = new C2S_LoginMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:C2S_LoginMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_LoginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C2S_LoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\"]\n\020C2S_LoginMessage\022\016\n\004nam" +
      "e\030\001 \001(\t:\000\022\022\n\010password\030\002 \001(\t:\000\022\020\n\005webid\030\003" +
      " \001(\005:\0010\022\023\n\010serverId\030\004 \001(\005:\0010B-\n\030com.snow" +
      "cattle.game.autoB\021LoginMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_C2S_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C2S_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_C2S_LoginMessage_descriptor,
        new java.lang.String[] { "Name", "Password", "Webid", "ServerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
